### ISSUE TITLE
levantamento de dados

### ISSUE THREAD

**Issue by K0rgana** [lipeh777/comuniq#1]
Eu como **desenvolvedor** quero saber como **funciona** o sistema de patrimônio do campus para melhor desenvolver o sistema

- [x] fazer entrevista com funcionário (obter informações sobre o funcionamento)

**Comment by lipeh777** [comment]
Link do questionário/entrevista: https://docs.google.com/document/d/1ktOhVwvsdEZdlw6HvqYCePMl0JqIleSEI13TVh2HGYc/edit?usp=sharing

**Comment by leonardolfp** [comment]
Link para ouvir o áudio da entrevista com Monteiro, responsável pelo patrimônio da instituição: https://drive.google.com/open?id=12W5qPi5lvi-NDA6hz2tZV-ylYSywSG0a

**Comment by leonardolfp** [comment]
Link para o resumo da entrevista:
https://docs.google.com/document/d/1gMVvew3cuE7bTADoRPMM6Wq0oB-reaAjK5FswqNrTJU/edit?usp=sharing
