### ISSUE TITLE
Cadastro de itens

### ISSUE THREAD

**Issue by JonissonGomes** [lipeh777/comuniq#11]
Eu **como** administrador **quero** criar um sistema de cadastro **para** que o usuário administrador possa cadastrar os itens da sua instituição.

- [x] Criar tela de cadastro de itens.

**Comment by K0rgana** [comment]
Sobre a biblioteca de importação adicionada

### Pré-requisitos para a biblioteca funcionar:

    PHP: ^7.0
    Laravel: ^5.5
    PhpSpreadsheet: ^1.6
    PHP extension php_zip ativada
    PHP extension php_xml ativada
    PHP extension php_gd2 ativada

Verifique quais extenções você já tem instalada com o comando abaixo:

**`php -m`**

> (mas provavelmente será necessario instalar as exteções zip,gd2 e xml)
> `sudo apt-get install php-zip` & `sudo service apache2 restart`
> `sudo apt-get install php7.1-gd` & `sudo service apache2 restart`
> `sudo apt-get install php-xml`  & `sudo service apache2 restart`

Depois instale as dependecias que faltam no projeto com o composer
**`composer install`**


[Documentação da Biblioteca aqui ;) ](https://docs.laravel-excel.com/3.1/imports/)
