### ISSUE TITLE
Estudar mecanismo de internacionalização

### ISSUE THREAD

**Issue by ranierivalenca** [lipeh777/comuniq#19]
Estudar sobre como criar templates no Laravel que se adaptem a múltiplas linguagens.

**Comment by jucielefernandes** [comment]
**links:**
- https://imasters.com.br/desenvolvimento/trabalhando-com-internacionalizacao-no-laravel
 
- https://medium.com/@sayhicoelho/laravel-5-4-como-criar-uma-aplica%C3%A7%C3%A3o-multilingual-bcacb5407de1

**Comment by jucielefernandes** [comment]
**exemplo de internacionalização:**

https://github.com/jucielefernandes/internacionaliza-o_laravel
