### ISSUE TITLE
Levantamento de dados com usuários comuns

### ISSUE THREAD

**Issue by jucielefernandes** [lipeh777/comuniq#20]
Eu como **desenvolvedor** quero saber como os **usuários** deseja as **funcionalidades** do sistema para um melhor desenvolvimento. 
- [x] utilizando o processo de classificação de cartões

**Comment by K0rgana** [comment]
link com lista perguntas a serem feitas na dinâmica/pesquisa com os usuários:
https://docs.google.com/document/d/1aOB5weRoNKjZ5pcR__ptQ1UqSYUW8Tm2Qx_LDKL2VpI/edit?usp=sharing

**Comment by jucielefernandes** [comment]
**adicionando respostas de alguns usuários comuns: **

![20190919_140852 (1)](https://user-images.githubusercontent.com/48837806/65268050-af517900-daec-11e9-9bce-ac45467c1ea5.jpg)

**Comment by K0rgana** [comment]
![image](https://user-images.githubusercontent.com/48961500/65619299-49566d00-df96-11e9-9f84-c6075a018fb7.png)

![image](https://user-images.githubusercontent.com/48961500/65619365-6723d200-df96-11e9-8e25-dc30af23cf64.png)

![image](https://user-images.githubusercontent.com/48961500/65619393-7276fd80-df96-11e9-90b8-b9d06aad4188.png)

![image](https://user-images.githubusercontent.com/48961500/65619420-7c98fc00-df96-11e9-9d09-5934251ce775.png)

![image](https://user-images.githubusercontent.com/48961500/65619434-83c00a00-df96-11e9-81f0-b350e43be6e6.png)

![image](https://user-images.githubusercontent.com/48961500/65619452-8c184500-df96-11e9-9916-4f4475038dd0.png)
