### ISSUE TITLE
Estudo do Framework VueJS

### ISSUE THREAD

**Issue by JonissonGomes** [lipeh777/comuniq#21]
Eu como **Desenvolvedor** irei fazer uma pesquisa sobre o **_Framework VueJS_** e estudar o funcionamento e execução do mesmo, para facilitar a forma de desenvolvimento do sistema e diminuir o tempo de desenvolvimento do sistema.

**Comment by JonissonGomes** [comment]
[vue-exemplo-lol.zip](https://github.com/lipeh777/comuniq/files/3645092/vue-exemplo-lol.zip)

**Comment by filipeandrev** [comment]
Exemplo de código em **vue js:**
- https://github.com/filipeandrev/estudovuejs
