### ISSUE TITLE
Criação de modelo de personas

### ISSUE THREAD

**Issue by perolasanja** [lipeh777/comuniq#22]
Eu **como** desenvolvedor **quero** criar modelos de personas **para** auxiliar melhor sobre as necessidades do cliente.

**Comment by JonissonGomes** [comment]
Onde devo adicionar a persona que fiz?

**Comment by K0rgana** [comment]
@JonissonGomes coloca aqui mesmo como comentário

**Comment by leonardolfp** [comment]
Guia básico para você criar a sua persona:
https://migreseunegocio.com.br/personas/

**Comment by perolasanja** [comment]
Como criar um modelo de persona ⬇
https://www.youtube.com/watch?v=1-cJ1UyRj6k

**Comment by JonissonGomes** [comment]
Documento com os perfis de personas:

https://docs.google.com/document/d/12CkVwXi5brw7cnVhK5bJeJfK0voEypzX19_wa_VUAPw/edit?usp=sharing

**Comment by GuilhermeH6** [comment]
Minha persona 

https://docs.google.com/document/d/1ppPyde6O7pNialymX3kbR0jgW0c9gV9dbFCL1aktSD8/edit?usp=sharing

**Comment by leonardolfp** [comment]
Minha persona:
https://docs.google.com/document/d/1Tunb3bM06i3OeYPZZqS_MWbMs-ddVpTTwZEAMeENBm8/edit?usp=sharing

**Comment by AdelyAlexandr** [comment]
Minha persona = 
https://docs.google.com/document/d/1V4Wx74yJdyHoidwiIApn-zWEg9btdbIWLLa1ai1lztY/edit?usp=sharing

**Comment by perolasanja** [comment]
Modelo de Persona ⬇
https://docs.google.com/document/d/1L8UVDo-dDZIj6ZevioLDQSUCKDSybxF_Betghiksqm4/edit?usp=sharing

**Comment by jucielefernandes** [comment]
**modelo persona:**
- https://docs.google.com/document/d/1nQJKHFkSpVNJbA4bRluqaFIDIpCuo0JQfhshvazu8_4/edit?usp=sharing

**Comment by JonissonGomes** [comment]
**Persona:**
https://docs.google.com/document/d/12CkVwXi5brw7cnVhK5bJeJfK0voEypzX19_wa_VUAPw/edit

**Comment by lipeh777** [comment]
Minha Persona:

https://docs.google.com/document/d/1idTyXjBRoQPPQOPaROAHq6rH4a9zgw6X17n9zuBaNNA/edit?usp=sharing

**Comment by K0rgana** [comment]
link definitivo:

> **Persona:**
> https://docs.google.com/document/d/12CkVwXi5brw7cnVhK5bJeJfK0voEypzX19_wa_VUAPw/edit
