### ISSUE TITLE
Compreender o mecanismo de Seed do Laravel

### ISSUE THREAD

**Issue by leonardolfp** [lipeh777/comuniq#24]
Eu como desenvolvedor, preciso estudar e compreender os mecanismos de Seed do Laravel.

**Comment by K0rgana** [comment]
Seeder e um recurso do laravel que é possível definir algumas rotinas pré-configuradas para manipular banco de dados. Sendo possível criar uma _Seeder_ com os dados default que iram preencher o sistema, sem a necessidade de criar registros manualmente para poder usar os recursos do sistema.

As classes de Seeder do Laravel ficam em:
> **database/seeds/**

As classes Seeders podem ser nomeadas com qualquer nome que você quiser, mas é legal seguir a convenção do laravel como:
> **UsersTableSeeder**

### **Criando  uma Seeder**:

Para criar uma nova Seerder, execute o comando _make:seeder_ do próprio artisan. 

**` php artisan make:seeder UsersTableSeeder`**

> Esse comando vai gerar a classe em database/seeds/UsersTableSeeder.php

### **Criando seeds**:

**1.** Crie a classe que ira definir os dados, continuando com a ideia da classe _UsersTableSeeder.php_, a logica para inserir novo usuário **deve ficar dentro do método run()**. O código tem que ser algo parecido com isso:

```
use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        User::create([
            'name'      => 'Carlos Ferreira',
            'email'     => 'carlos@especializati.com.br',
            'password'  => bcrypt('MinhaSenhaAqui'),
        ]);
    }
}
```

**2.** Depois de criar a classe devemos registrada-la na "classe pai" a ela,  a classe _**DatabaseSeeder**_ (database/seeds/DatabaseSeeder.php), a chamada a classe deve ser feita dentro do **metodo run()** e usando o método **$this->call()**, que pode ser utilizado invocar quantas classes você achar necessário. O código tem que ser algo parecido com isso:

```
use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class DatabaseSeeder extends Seeder
{
    public function run()
  {
     $this->call(UsersTableSeeder::class);
  }
}
```

para entender melhor como criar seeds:

- https://blog.especializati.com.br/seeders-no-laravel/
- https://medium.com/by-vinicius-reis/trabalhando-com-seeds-no-laravel-5-142829ddc32e

para criar seeds mais complexos, pode-se ultilizar bibliotecas como:
- Faker : https://github.com/fzaninotto/Faker 


### **Rodando a Seeder**:

Depois de escrever o Seed, pode ser necessário recarregar o autoload do Composer, utilize o comando:

**`composer dump-autoload`**

Agora você pode usar o comando do artisan para popular o banco de dados. 

**`php artisan db:seed`**

> Este comando vai rodar todas as classes de Seeders registradas na classe DatabaseSeeder.

Também pode-se usar o comando a seguir para **especificar uma seed** e ir populando o banco classe a classe:

**`php artisan db:seed --class=UsersTableSeeder`**

Também pode-se popular o banco usando o comando _migrate:refresh_, que também reverterá e executará novamente todas as migrações:

**`php artisan migrate:refresh --seed`**

> Este comando é útil para reconstruir completamente seu banco de dados e já cria-lo populado
