### ISSUE TITLE
integração de cadastro com esquema do banco

### ISSUE THREAD

**Issue by jucielefernandes** [lipeh777/comuniq#25]
Eu **como** desenvolvedor  **quero** um mecanismo **para** integrar o sistema de cadastro de acordo com o esquema do banco de dados 
 
ps: Esta atividade depende da modelagem de banco de dados #3

**Comment by ranierivalenca** [comment]
Wat? No commits, no comments? Explain yourself =(

**Comment by jucielefernandes** [comment]
Essa issue esta duplicada, porque basicamente era  as migrations e seeders.
