### ISSUE TITLE
Adaptar o front-end para mobile

### ISSUE THREAD

**Issue by GuilhermeH6** [lipeh777/comuniq#28]
Eu como "usuário" quero as telas de acesso ao usuário adaptadas para acessar no celular.

- [x] Protótipo

- [ ] Adaptar as telas de interação para mobile

**Comment by leonardolfp** [comment]
Dicas para adaptar sites web para dispositivos móveis:
https://imasters.com.br/design-ux/10-dicas-para-adaptar-sites-web-para-dispositivos-moveis-parte-02

**Comment by AdelyAlexandr** [comment]
Tutorial de responsividade:
https://www.hostinger.com.br/tutoriais/criar-site-responsivo-css

**Comment by AdelyAlexandr** [comment]
exemplo de código responsivo:
[responsivo.zip](https://github.com/lipeh777/comuniq/files/3674543/responsivo.zip)

**Comment by leonardolfp** [comment]
Links usados para adaptar o front-end para mobile
https://www.devmedia.com.br/materialize-css-como-criar-um-menu-responsivo/37894
https://mariovalney.com/como-criar-um-site-responsivo-e-com-o-material-design-do-google-usando-o-materialize/

**Comment by GuilhermeH6** [comment]
Modelo teste das telas mobiles:

![PAG 4](https://user-images.githubusercontent.com/47796068/66278272-cf6b9100-e87d-11e9-8da5-9032fb48851b.jpg)
![PAG 1](https://user-images.githubusercontent.com/47796068/66278273-cf6b9100-e87d-11e9-957a-38740e870976.jpg)
![PAG 2](https://user-images.githubusercontent.com/47796068/66278274-cf6b9100-e87d-11e9-9da3-c52c03509967.jpg)
![PAG 3](https://user-images.githubusercontent.com/47796068/66278275-d0042780-e87d-11e9-917b-4c084422f087.jpg)

**Comment by GuilhermeH6** [comment]
modelo teste das telas mobile:

[telas-mobile.zip](https://github.com/lipeh777/comuniq/files/3695039/telas-mobile.zip)

**Comment by lilialnas** [comment]
Essa issue foi modificada para Spike, pois não há front ainda para adaptações para mobile.
