### ISSUE TITLE
Modelagem de banco de dados 

### ISSUE THREAD

**Issue by filipeandrev** [lipeh777/comuniq#3]
Eu como **desenvolvedor** quero que o projeto tenha um **banco de dados** para armazenar os dados do sistema.
- [x] Definir modelo lógico do banco.

**Comment by K0rgana** [comment]
modelagem do banco com auto-relacionamento do chamado:

![image](https://user-images.githubusercontent.com/48961500/65381093-cdbb9e00-dcbf-11e9-960f-179ba86c6ce5.png)

**Comment by K0rgana** [comment]
O modelo ainda pode ser modificado para melhoria do sistema, esta é apenas a modelagem inicial

**Comment by ranierivalenca** [comment]
Fazer alterações para adicionar novas tabelas.

**Comment by jucielefernandes** [comment]
✌  Pedimos a **analise** do professor de banco de dados sobre o modelo e as **observações** foram a seguintes:

O modelo ira **perder** algumas ligação de tabelas como: 😢
- **setor com categoria_item:** pois o item da categoria pode **pertencer** a mais de 1 setor ex: setor informatica ter itens imobiliários e eletrônicos.😒
-  tabela **observador:** pois  o observador já é um **usuário** e essa informação deve ser tratada na **aplicação** e não no banco.😎


  na tabela **status** se  as informações forem até 8 devem ser guardadas em atributos select,**não** necessitando de uma tabela. Caso os atributos forem **superiores** ao valor citado, ai sim, faz sentido a criação de uma tabela no banco. 👌

**Comment by K0rgana** [comment]
modelo atual:

![image](https://user-images.githubusercontent.com/48961500/65967999-f0288680-e438-11e9-99d0-a85a700bb977.png)

**Comment by ranierivalenca** [comment]
> Pedimos a **análise** do professor de banco de dados sobre o modelo e as **observações** foram a seguintes:
> 
> O modelo **perderá** algumas ligação de tabelas como:
> 
> * **setor com categoria_item:** o item da categoria poderá **pertencer** a mais de 1 setor ex: setor informática ter itens móveis e eletrônicos.
Beleza
> * tabela **observador:** pois  o observador já é um **usuário** e essa informação deve ser tratada na **aplicação** e não no banco.
Acho que precisamos sim do observador, senão não teremos controle sobre quais usuários devem ser avisados sobre a atualização de status de um chamado.
> 
> Na tabela **status** se as informações forem até 8 devem ser guardadas em atributos select,**não** necessitando de uma tabela. Caso os atributos for **superior** ao valor citado anteriormente, irá fazer sentido a criação de uma nova tabela.
Beleza
