### ISSUE TITLE
Nomenclaturas das tabelas

### ISSUE THREAD

**Issue by JonissonGomes** [lipeh777/comuniq#33]
Eu como **Desenvolvedor** quero uma melhor nomenclatura das tabelas no banco de dados para melhor compreensão do esquema do banco.

- [x] Tabela Iten_categoria
- [x] Tabela usuário
- [x] Tabela tipo_subtipo
- [x] Tabela chamado_tipo
- [x] Tabela chamado

**Comment by filipeandrev** [comment]
Aqui está o nome dos responsáveis e das models que devem ser rodadas com esses nomes com o comando:
`php artisan make:model <NomeModel> -m`

Chamados  (aracity)
Status  (morgana)
Instituicoes  (juciele)
ItensPatrimonio  (adely)
Usuarios  (alisson)
Observadores  (johnny)
ItensCategorias  (perola)
StatusChamados  (alisson)
SetorUsuarios  (morgana)
Setores  (perola)
TiposChamados  (leo)
SubtiposChamados  (guilherme)
  
>OBS: Os nomes das models devem ser escritos no singular e com CamelCase.
> OBS: O -m cria também a migration, no plural, correspondente a model criada. 

O que é CamelCase:
https://pt.wikipedia.org/wiki/CamelCase#targetText=CamelCase%20%C3%A9%20a%20denomina%C3%A7%C3%A3o%20em,defini%C3%A7%C3%B5es%20de%20classes%20e%20objetos.

Exemplo de nomes de Models e das tabelas das migrations.
![Models](https://user-images.githubusercontent.com/48837834/66683012-ce0ae180-ec4c-11e9-99d4-f613eb888e85.png)
