### ISSUE TITLE
Criar Migration de Instituições

### ISSUE THREAD

**Issue by AdelyAlexandr** [lipeh777/comuniq#34]
Eu **como** desenvolvedor **quero** uma tabela no banco de dados **para** armazenar o nome de instituições.

- [x] Criar model para a tabela de Instituições.
- [x] Criar migration para a tabela de Instituições.

**Comment by ranierivalenca** [comment]
Esse nome da classe não funciona dessa forma. Lembrando, classes usam `CamelCase` e começam com letra **maiúscula**.
