### ISSUE TITLE
Criar Migration dos Setores

### ISSUE THREAD

**Issue by perolasanja** [lipeh777/comuniq#35]
Eu **como** desenvolvedor **quero** uma tabela no banco de dados **para** armazenar o nome dos setores.

- [x] Criar model para a tabela dos setores.
- [x] Criar migration para a tabela dos setores.

**Comment by perolasanja** [comment]
Obs: Todos os nomes das tabelas tem que estar no plural e a efica tem que estar no singular.

**Comment by ranierivalenca** [comment]
Esse nome da classe não funciona dessa forma. Lembrando, classes usam `CamelCase` e começam com letra **maiúscula**. Faltam também os atributos do Model.
