### ISSUE TITLE
Criar Migration de Itens_de_Patrimônios

### ISSUE THREAD

**Issue by perolasanja** [lipeh777/comuniq#39]
Eu **como** desenvolvedor **quero** uma tabela no banco de dados **para** armazenar o nome de itens_de_patrimónios.

- [x] Criar model para a tabela de itens_de_patrimónios.
- [x] Criar migration para a tabela de itens_de_patrimónios.

**Comment by ranierivalenca** [comment]
Esse nome da classe não funciona dessa forma. Lembrando, classes usam `CamelCase`  e começam com letra maiúscula.

**Comment by ranierivalenca** [comment]
Faltam os atributos do model...
