### ISSUE TITLE
Definir um protótipo de template

### ISSUE THREAD

**Issue by AlissonThyago** [lipeh777/comuniq#4]
Eu **como** desenvolvedor quero **padronização** do site para melhor navegação.

- [x] definir as cores

- [x] prototipação das telas

**Comment by K0rgana** [comment]
Segue os Protótipos das telas até o momento:

 Index - não logado 

![index](https://user-images.githubusercontent.com/48961500/65397306-797af180-dd85-11e9-9ba1-26888c67002e.png)

Index - logado
![index_logado](https://user-images.githubusercontent.com/48961500/65397349-b515bb80-dd85-11e9-9514-a1276ab9b85f.png)

cadastro 

![cadastro](https://user-images.githubusercontent.com/48961500/65397360-c5c63180-dd85-11e9-8024-29402343e507.png)

login

![login](https://user-images.githubusercontent.com/48961500/65397367-d1195d00-dd85-11e9-988b-945ab3315f7e.png)

**Comment by K0rgana** [comment]
Mais telas:

Ajuda

![ajuda](https://user-images.githubusercontent.com/48961500/65398502-f3af7400-dd8d-11e9-900f-abc12bda0454.png)

Desenvolvedores

![dev](https://user-images.githubusercontent.com/48961500/65398503-f4480a80-dd8d-11e9-9ef4-ea56710db6ac.png)

_UPDATE_ index - com footer

![index](https://user-images.githubusercontent.com/48961500/65398504-f4480a80-dd8d-11e9-8b22-41d8610498e9.png)
