### ISSUE TITLE
Criar Migration de Status_Chamados

### ISSUE THREAD

**Issue by perolasanja** [lipeh777/comuniq#41]
Eu **como** desenvolvedor **quero** uma tabela no banco de dados **para** armazenar o nome de status_chamados.

- [x] Criar model para a tabela de status_chamados.
- [x] Criar migration para a tabela de status_chamados.

**Comment by ranierivalenca** [comment]
Esse nome da classe não funciona dessa forma. Lembrando, classes usam `CamelCase` e começam com letra **maiúscula**.

**Comment by perolasanja** [comment]
Reabrindo issue, porque o conteúdo de Status_Chamado foi excluída por engano.
