### ISSUE TITLE
Criar Migration de Status

### ISSUE THREAD

**Issue by perolasanja** [lipeh777/comuniq#43]
Eu **como** desenvolvedor **quero** uma tabela no banco de dados **para** armazenar o nome de status.

- [x] Criar model para a tabela de status.
- [x] Criar migration para a tabela de status.

**Comment by K0rgana** [comment]
links uteis para criar models e migrations:

- https://blog.especializati.com.br/criar-tabelas-laravel-migrations/
- https://medium.com/trainingcenter/relacionando-models-e-tabelas-no-laravel-5-4-a8365a12eca2
- https://laravel.com/docs/5.7/migrations
