### ISSUE TITLE
Criar Migration de Tipos_Subtipos

### ISSUE THREAD

**Issue by perolasanja** [lipeh777/comuniq#44]
Eu **como** desenvolvedor **quero** uma tabela no banco de dados **para** armazenar o nome de tipos_subtipos.

- [x] Criar model para a tabela de tipos_subtipos.
- [x] Criar migration para a tabela de tipos_subtipos.

**Comment by ranierivalenca** [comment]
Esse nome da classe não funciona dessa forma. Lembrando, classes usam `CamelCase` e começam com letra **maiúscula**.
