### ISSUE TITLE
Criar Migration de Chamados_Tipos

### ISSUE THREAD

**Issue by perolasanja** [lipeh777/comuniq#45]
Eu **como** desenvolvedor **quero** uma tabela no banco de dados **para** armazenar o nome de chamados_tipos.

- [x] Criar model para a tabela de chamados_tipos.
- [x] Criar migration para a tabela de chamados_tipos.

**Comment by ranierivalenca** [comment]
Esse nome da classe não funciona dessa forma. Lembrando, classes usam `CamelCase` e começam com letra **maiúscula**.
