### ISSUE TITLE
Estudar QRcode e códigos de barra

### ISSUE THREAD

**Issue by GuilhermeH6** [lipeh777/comuniq#5]
Eu como **desenvolvedor** quero **estudar** como funciona a tecnologia de QRcode e códigos de barra para integrar no projeto.

- [x] Estudar QRcode e como ler o mesmo por smartphones.

- [x] Estudar códigos de barras.

**Comment by GuilhermeH6** [comment]
Links com uma explicação breve e básica sobre QRcode e código de barras:

http://g1.globo.com/tecnologia/noticia/2011/05/entenda-o-que-sao-os-qr-codes-codigos-lidos-pelos-celulares.html
https://www.techtudo.com.br/dicas-e-tutoriais/noticia/2011/03/um-pequeno-guia-sobre-o-qr-code-uso-e-funcionamento.html

Alguns exemplos de vídeo-aulas sobre leitor de QRcode:

https://www.youtube.com/watch?v=Pl6VT7c_c_4
https://www.youtube.com/watch?v=6mRf7F1eVPQ&feature=youtu.be

Exemplos de códigos de leitores de QRcodes e códigos de barra:

https://github.com/schmich/instascan
https://github.com/zxing-js/library
https://github.com/zxing-js

Alguns plug-in :
http://www.bestjquery.com/demo/barcode-scanner/

**Comment by GuilhermeH6** [comment]
Repositório do git para vocês testarem um leitor de qrcode:

https://github.com/rcarneironet/qrcode-js

**Comment by K0rgana** [comment]
Estudei um pouco com dos link que @GuilhermeH6 colocou na issue e aqui vai resumo sobre tudo:

### Informações em QRcode

Os codigos QRcode são bidimensional (2-D), guardando informação na verticalmente e na horizontal. Devido a esta característica os códigos QR possibilitam armazenar centenas de vezes mais dados que os tradicionais códigos de barras, os tipo de informação embutida no codigo pode ser textos simples, URL, mensagens SMS, Contatos, localizações, instruções de utilização, endereços de e-mail e muito mais. Essas informações podem ser recuperadas usando um leitor de QRcode.

**diferença gritante entre QRcode e Codigo de barras:**
> Os QR Codes permitem armazenar diferentes tipos de dados, incluindo caracteres alfabéticos, números, símbolos, binários, Kanji e Kana (alfabeto japonês). Enquanto o tradicional código de barras pode ter no máximo 20 dígitos, um QR Code pode armazenar até 7.089 caracteres. Estes caracteres podem ser combinados num símbolo de grande porte ou então divididos até 16 símbolos.
>[fonte](https://www.noseqret.pt/tudo-sobre-qr-codes/)

 

### Lendo QRcode

> Exemplos de códigos de leitores de QRcodes e códigos de barra:
> 
> https://github.com/schmich/instascan
> https://github.com/zxing-js/library
> https://github.com/zxing-js
> https://viladosilicio.com.br/criando-um-app-de-leitura-de-codigo-de-barras-com-javascript/

As bibliotecas funcionam de forma simliar

Dentre as bibliotecas de leitura, eu testei a InstaScan na qual a imprementação é bem simples, precisando somente instanciar um elemento de video usando a biblioteca e verificar se existem cameras conectadas no dispositivo para depois ele retornar o conteúdo que esta armazenado no QRcode, vocês podem dar uma olhada no codigo comentado nesse repositorio:
- https://github.com/K0rgana/InstaScanExample


Vocês tambem podem testar esse repositorio que permite gerar gerar novos QRcode e fazer a leitura ( esse exemplo mais completo que o meu, **então deem uma olhada tambem** )

> Repositório do git para vocês testarem um leitor de qrcode:
> 
> https://github.com/rcarneironet/qrcode-js

**Para rodar os repositorios basta clonar e rodar no localhost:** 
`php -S localhost:9000`


Se ainda estiverem com dificuldades na hora de usarem as bibliotecas assistam essas video aulas, são bem explicativas

> Alguns exemplos de vídeo-aulas sobre leitor de QRcode:
> https://www.youtube.com/watch?v=Pl6VT7c_c_4
> https://www.youtube.com/watch?v=6mRf7F1eVPQ&feature=youtu.be

### Considerações sobre como usar no projeto

- Podemos utilizar as bibliotecas de leitura para recuperar os codigos do tombamento para preencher o campo do form automaticamente na hora de abrir o chamado na versão mobile.

- para a versão "mista" podemos utilizar tanto a biblioteca de leitura quanto a de geração do codigo: 
Para ler o codigo de tombamento do equipamento no celular e iniciar a preencher o formulario. Em seguida , atraves da versão web, gerar QRcode para "transferir a sessão" e continuar o preenchimento do chamado no desktop. (tipo como acontece quando utilizamos o whatsapp na versão web)
