### ISSUE TITLE
Criar seeder de Chamados_Tipos

### ISSUE THREAD

**Issue by perolasanja** [lipeh777/comuniq#58]
Eu **como** desenvolvedor **quero** popular a tabela chamados_tipos no banco de dados **para** armazenar os tipos de status do chamado.

- [x] Criar seed da tabela de chamados_tipos.
- [x] Adicionar chamada da tabela de chamados_tipos.

**Comment by leonardolfp** [comment]
Caso tenham esse mesmo problema (ERROR 1819), a solução é acrescentar: "@localhost", depois do "root".
![WhatsApp Image 2019-10-13 at 19 38 37](https://user-images.githubusercontent.com/48837658/66723634-e2d4aa00-edf1-11e9-9ae1-dc2f7965dff2.jpeg)

![WhatsApp Image 2019-10-13 at 19 39 51](https://user-images.githubusercontent.com/48837658/66723638-e9632180-edf1-11e9-8883-ad06435ecd50.jpeg)
