### ISSUE TITLE
Cadastro de usuários

### ISSUE THREAD

**Issue by AdelyAlexandr** [lipeh777/comuniq#6]
Eu **como** usuário do sistema de patrimônio do campus Igarassu **quero** realizar meu cadastro **para** registrar e acompanhar ocorrências nos itens do patrimônio.
- [x] Criar protótipo de tela
- [x] Desenvolver a parte lógica do sistema de cadastro.
- [x] Desenvolver o Front-End do sistema de cadastro utilizando Framework .
- [x] Após cadastro, redirecionar o usuário para a página inicial.

PS: Esta atividade depende da modelagem do banco de dados #3

**Comment by AlissonThyago** [comment]
Prototipação da pagina de cadastro.
![cadastro](https://user-images.githubusercontent.com/48837955/65167561-2fa6aa00-da19-11e9-85de-36cad5102404.png)
